### ISSUE TITLE
Dates Should be More Readable

### ISSUE THREAD

**Issue by vontell** [elainewlin/one-cast#10]
Table for search and production information.

**Comment by vontell** [comment]
Did we want to have the dates in the format of MM/dd/yy, or in the form of 'Month Day, Year"? @elainewlin @atoregozh @CristhianUlloa

**Comment by CristhianUlloa** [comment]
I was under the impression that we wanted the latter (e.g. April 20, 2016)

**Comment by vontell** [comment]
Yeah I was under the same impression

**Comment by elainewlin** [comment]
Okay, I'll fix that.
