### ISSUE TITLE
Fix Problems with Dialogs

### ISSUE THREAD

**Issue by vontell** [elainewlin/one-cast#13]

**Comment by atoregozh** [comment]
calendar pop-up with fullCalendar is now working. did you mean this problem or there were some others?

**Comment by vontell** [comment]
This was in reference to the dialogs opening more than once. However, considering that this issue has been minimized, I am going to close it. It seems that the dialogs open multiple times due to asynchronous or concurrent issues, where a dialog is opened, the browser doesn't detect it yet, and another one is opened. Feel free to reopen this issue if it becomes more of an issue.
