### ISSUE TITLE
Fix Active Link Background (From White to Purple)

### ISSUE THREAD

**Issue by vontell** [elainewlin/one-cast#16]

**Comment by vontell** [comment]
Has this officially been fixed? I haven't noticed white backgrounds in a while but I am not sure if that means it is fixed. @CristhianUlloa @atoregozh @elainewlin

**Comment by CristhianUlloa** [comment]
I think it's still a bug.

**Comment by CristhianUlloa** [comment]
looks like it has been fixed after all.
