### ISSUE TITLE
Director's casting page has no scrollbar

### ISSUE THREAD

**Issue by CristhianUlloa** [elainewlin/one-cast#55]
@/romeojulietdirect

there is no scrollbar that shows up for the window but the window is scrollable. May be associated with the director's calendar not showing up at the bottom.

**Comment by atoregozh** [comment]
the same issue about every other modal that needs a scrollbar - e.g. Add New Role modal

**Comment by atoregozh** [comment]
@CristhianUlloa I was trying to enable it but on a Mac there's weird feature where you cannot see a scrollbar unless you start scrolling. not sure how to fix it.

**Comment by CristhianUlloa** [comment]
well, the page scrolls now so that's good enough.
