### ISSUE TITLE
Calendar dates jerk on scroll (on Create New Casting production date)

### ISSUE THREAD

**Issue by atoregozh** [elainewlin/one-cast#60]
Days don't align properly on scroll. For some months (e.g. August 2016) dates are properly aligned, but for others, they shift to the right and don't match the header dates. not sure why this is happening and I wasn't able to understand the root cause of this formatting.

**Comment by atoregozh** [comment]
When you hit Create New Casting, there’s a calendar on Production date. Calendar behaves in a strange manner. Days shift back and forth as you scroll the calendar. dates don’t align with the M, T, W, T, F columns on top

**Comment by CristhianUlloa** [comment]
error is barely noticeable. Considered closed.
