### ISSUE TITLE
change actor profile creation calendar to datepicker range for consistency

### ISSUE THREAD

**Issue by atoregozh** [elainewlin/one-cast#69]

**Comment by vontell** [comment]
Should this be the date range picker or the material datepicker?

**Comment by atoregozh** [comment]
I thought date range picker so that we could put both start graduation and end graduation together and preserve space. we could go with material datepicker as well though. date range picker has weird formatting of YYYY-MM-DD which i don't really like. do you have a preference?

**Comment by atoregozh** [comment]
After hours of fixing, I decided to go with material datepicker
